/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PartesGraficas2;

import Datos.Listas;
import javax.swing.JOptionPane;

/**
 *
 *
 *
 */
public class BarcoDe2Casillas2 extends javax.swing.JFrame {

    /**
     * Creates new form BarcoDe2Casillas
     */
    Listas l = new Listas();

    public BarcoDe2Casillas2() {
        initComponents();
        VolverAMenú2Casillas.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtColumna1De2Casillas = new javax.swing.JTextField();
        txtFila1De2Casillas = new javax.swing.JTextField();
        txtColumna2De2Casillas = new javax.swing.JTextField();
        txtFila2De2Casillas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        VolverAMenú2Casillas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mensajeBar = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la Columna 1:");

        jLabel2.setText("Ingrese la Fila 1:");

        jLabel3.setText("Ingrese la Columna 2:");

        jLabel4.setText("Ingrese la Fila 2:");

        txtColumna2De2Casillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColumna2De2CasillasActionPerformed(evt);
            }
        });

        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        VolverAMenú2Casillas.setText("Siguiente");
        VolverAMenú2Casillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAMenú2CasillasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 24)); // NOI18N
        jLabel7.setText("Barco de 2 Casillas");

        mensajeBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(VolverAMenú2Casillas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFila1De2Casillas)
                                .addComponent(txtColumna1De2Casillas)
                                .addComponent(txtFila2De2Casillas, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addComponent(txtColumna2De2Casillas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(91, 91, 91)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFila1De2Casillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColumna1De2Casillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFila2De2Casillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColumna2De2Casillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(mensajeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(VolverAMenú2Casillas)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtColumna2De2CasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColumna2De2CasillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColumna2De2CasillasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int TamañoCont = l.ContadorJ2.size();
        int ColumnaIngresada1 = Integer.parseInt(txtColumna1De2Casillas.getText());
        int FilaIngresada1 = Integer.parseInt(txtFila1De2Casillas.getText());
        int ColumnaIngresada2 = Integer.parseInt(txtColumna2De2Casillas.getText());
        int FilaIngresada2 = Integer.parseInt(txtFila2De2Casillas.getText());
        int RestaCol = ColumnaIngresada1 - ColumnaIngresada2;
        int RestaFil = FilaIngresada1 - FilaIngresada2;

        //Casillas tamaño 2
        for (int i = 0; i < l.listaPosJ2.size(); i++) {

            int ColSave = l.listaPosJ2.get(i).getCol();
            int FilaSave = l.listaPosJ2.get(i).getFil();

            if (ColumnaIngresada1 == ColSave && FilaIngresada1 == FilaSave || ColumnaIngresada2 == ColSave && FilaIngresada2 == FilaSave) {
                JOptionPane.showMessageDialog(null, "Ya hay un barco ahi,ingrese otra posicion");
                return;
            }
        }
        if (RestaCol > 1 || RestaCol < -1) {
            JOptionPane.showMessageDialog(null, "Verifique la casilla ingresadas,debe de estar cerca de las demas casillas");
            return;
        }
        if (RestaFil > 1 || RestaFil < -1) {
            JOptionPane.showMessageDialog(null, "Verifique la casilla ingresadas,debe de estar cerca de las demas casillas");
            return;
        }
        if (ColumnaIngresada1 == ColumnaIngresada2 && FilaIngresada1 == FilaIngresada2) {

            mensajeBar.setText("Error,verifique que las posiciones del barco,está colocado el barco en la misma casilla");
            return;

        }
        if (ColumnaIngresada1 != ColumnaIngresada2 && FilaIngresada1 != FilaIngresada2) {
            mensajeBar.setText("Error,verifique que las posiciones del barco está colocado de forma vertical o de forma horizontal");
            return;

        } else if (ColumnaIngresada1 == ColumnaIngresada2 && FilaIngresada1 != FilaIngresada2) {

            l.SumaCont2(cont);
            TamañoCont = l.ContadorJ2.size();
            cont++;
            if (TamañoCont > 10) {
                JOptionPane.showMessageDialog(null, "Has alcanzado el maximo de barcos");
                return;
            }
            l.añadirPosJ2(ColumnaIngresada1, FilaIngresada1, 2);
            l.añadirPosJ2(ColumnaIngresada2, FilaIngresada2, 2);
            VolverAMenú2Casillas.setVisible(true);
            mensajeBar.setText("Barco añadido");
            

        } else if (ColumnaIngresada1 != ColumnaIngresada2 && FilaIngresada1 == FilaIngresada2) {

            l.SumaCont2(cont);
            TamañoCont = l.ContadorJ2.size();
            cont++;
            if (TamañoCont > 10) {
                JOptionPane.showMessageDialog(null, "Has alcanzado el maximo de barcos");
                return;
            }
            l.añadirPosJ2(ColumnaIngresada1, FilaIngresada1, 2);
            l.añadirPosJ2(ColumnaIngresada2, FilaIngresada2, 2);
            VolverAMenú2Casillas.setVisible(true);
            mensajeBar.setText("Barco añadido");
            
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VolverAMenú2CasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAMenú2CasillasActionPerformed
        POVJugador2 volvermenú = new POVJugador2();
        dispose();
        volvermenú.setVisible(true);
    }//GEN-LAST:event_VolverAMenú2CasillasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtColumna1De2Casillas.setText("");
        txtColumna2De2Casillas.setText("");
        txtFila1De2Casillas.setText("");
        txtFila2De2Casillas.setText("");
        mensajeBar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       POVJugador2 abrirMenu= new POVJugador2();
       dispose();
       abrirMenu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarcoDe2Casillas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarcoDe2Casillas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarcoDe2Casillas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarcoDe2Casillas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarcoDe2Casillas2().setVisible(true);
            }
        });
    }
    int cont = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverAMenú2Casillas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mensajeBar;
    private javax.swing.JTextField txtColumna1De2Casillas;
    private javax.swing.JTextField txtColumna2De2Casillas;
    private javax.swing.JTextField txtFila1De2Casillas;
    private javax.swing.JTextField txtFila2De2Casillas;
    // End of variables declaration//GEN-END:variables
}
